services:
  youapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youapp_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    env_file:
      - .env
    networks:
      - youapp-network
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - youapp-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_mq
    restart: always
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # RabbitMQ dashboard
    networks:
      - youapp-network
    environment:
      RABBITMQ_DEFAULT_USER: youapp
      RABBITMQ_DEFAULT_PASS: secret123
  redis:
    image: redis:latest
    container_name: youapp_redis
    command: redis-server --requirepass redis_password
    ports:
      - "6380:6379"
    networks:
      - youapp-network
    volumes:
      - youapp_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  youapp-network:

volumes:
  mongo_data:
  youapp_redis:
